name: "Docker build and push to GHCR"

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Get current date"
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: "Build and push app"
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/pkitazos/matching-service:latest,ghcr.io/pkitazos/matching-service:${{ steps.date.outputs.date }},ghcr.io/pkitazos/matching-service:${{ github.sha }}
